### ISSUE TITLE
Exception in thread "main" java.lang.NoClassDefFoundError: com/ibm/xml/parser/MIME2Java

### ISSUE THREAD

**Issue by wayblink** [jyeary/soap4j#1]
Hi, thank you for publish this project.
I am now work in a project which needs XMI serialization/unserialization.
However, I get an Exception when I tried your code:

Exception in thread "main" java.lang.NoClassDefFoundError: com/ibm/xml/parser/MIME2Java
	at com.ibm.xmi.framework.XMIFile.write(XMIFile.java:822)
	at com.ibm.xmi.job.Job.writeObjectsImpl(Job.java:82)
	at com.ibm.xmi.job.Job.writeObjects(Job.java:38)

It seems I still need some libraries but I can't find it. 
Could you help me about it?

**Comment by jyeary** [comment]
I am looking at the XMI jar which I have decompiled in the IDE and I don't see any specific references to that class. It was part of the **XML4J** project. There is a version of the parser which was converted from the **XML4J** project to **Xerces**. This dependency is included as **xerces-1.0.4.jar** that includes the class **org.apache.xerces.readers.MIME2Java**.

Please check your dependencies and let me know if that helps.

**Comment by jyeary** [comment]
I found this comment on an archive IBM DeveloperWorks site for XML4J.

> On November 9, 1999, the Apache Software Foundation announced the creation of the xml.apache.org project for Open Source XML solutions. As part of that announcement, IBM announced that it was donating its XML4J, XML4C and LotusXSL technologies to the xml.apache.org project. The parsing technologies have been renamed Xerces, and the LotusXSL technology has been renamed Xalan. IBM is shifting its XML parsing development resources to work on the Xerces parsers. The objective is to use the Xerces code base as the foundation for XML4J and XML4C. This version of XML4J is based on the Apache Xerces version 1.2.0 codebase.

**Comment by jyeary** [comment]
I have included a copy of the XML4J llibrary for your use in case you need it.

[xml4j_2_0_15.jar.zip](https://github.com/jyeary/soap4j/files/1472379/xml4j_2_0_15.jar.zip)

**Comment by wayblink** [comment]
Nice of you. It works. Thank you very much.
